### PR TITLE
add process document for reference on proposals documentation

### PR DESCRIPTION
**Pull request by Kielan**
good for reference

### CODE REVIEW

**Comment by Kielan** [comment]
There is on the document TC39 `stages`, not `statuses`. I understand what stage is, but I can't understand what is `status`? Please change status to stage? Please say yes and I will do it.

**Review by ljharb — APPROVED** [review]
“Status” here refers to the babel status; “stage” refers to the tc39 stage.

This PR is already appropriate; I’m not sure why we’d need a different change.

**Comment by Kielan** [comment]
that is very unclear, why not just say stage?

**Comment by ljharb** [comment]
Because they’re different; the stage is how it’s progressing in the language committee, the status is whether it’s implemented in babel or not.

If you look at some of the column values, it might become clearer.

**Comment by mqklin** [comment]
@ljharb it was not clear for me to understand what `status` is. Now I understand, that it's like `stage`, but for `babel` itself. Would be good to note this somewhere.

**Pull request merged**
