### PR TITLE
remove object rest/spread, and async iterators

### PR DESCRIPTION
**Pull request by dnalborczyk**
both are part of the ES2018 spec now.

### CODE REVIEW

**Comment by suchipi** [comment]
Thanks!

**Comment by littledan** [comment]
This seems a little unfortunate, that that nice documentation was straight-up removed. Is there any possibility of making a "finished proposals" section, to save this sort of thing around as an archive (which is more accessible than git)?

**Comment by egeriis** [comment]
@littledan What kind of documentation are you looking for? This website has a nice overview of all proposals and even lists how they are supported across browsers. http://kangax.github.io/compat-table/es6/

**Comment by littledan** [comment]
Well, I imagine the plugins based on the proposals will stay around for a while. Wouldn't it be nice to link the plugins to the finished spec work?

**Comment by nicolo-ribaudo** [comment]
I agree with Daniel; I opened #49 since I find discussions in open issues easier to find than comments on closed PRs 🙂

**Pull request merged**
